In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4100, 2230, 3891, 2417],
 [4100, 2230, 3891, 6511],
 [4100, 5467, 3891, 640],
 [9193, 2854, 6284, 9346, 3522],
 [9193, 2854, 6284, 9346, 8396],
 [5643, 4100, 6886, 3891, 7366],
 [1905, 5956, 5840, 9346]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding # Imports the Embedding layer, which is used to convert words/tokens into dense vector representations.
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences # Imports the function to pad sequences to a uniform length.
from tensorflow.keras.models import Sequential # Imports the Sequential model, which is a linear stack of layers.

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4100 2230 3891 2417]
 [   0    0    0    0 4100 2230 3891 6511]
 [   0    0    0    0 4100 5467 3891  640]
 [   0    0    0 9193 2854 6284 9346 3522]
 [   0    0    0 9193 2854 6284 9346 8396]
 [   0    0    0 5643 4100 6886 3891 7366]
 [   0    0    0    0 1905 5956 5840 9346]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 381ms/step


array([[[ 0.03112811,  0.00270622,  0.02091917, -0.01028411,
          0.00108735, -0.04197252, -0.03361511,  0.03464837,
         -0.01296127, -0.04242287],
        [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,
          0.00108735, -0.04197252, -0.03361511,  0.03464837,
         -0.01296127, -0.04242287],
        [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,
          0.00108735, -0.04197252, -0.03361511,  0.03464837,
         -0.01296127, -0.04242287],
        [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,
          0.00108735, -0.04197252, -0.03361511,  0.03464837,
         -0.01296127, -0.04242287],
        [-0.01638373,  0.01433196,  0.02804383,  0.04002675,
         -0.00018103,  0.00321428,  0.00964044,  0.01040549,
         -0.04174905, -0.01057873],
        [-0.01139801, -0.02679174, -0.01855575,  0.03856239,
         -0.04388597, -0.03039476, -0.00528153,  0.02034989,
         -0.0175235 ,  0.00594043],
        [ 0.00246538, -0.04481317,  0.04963833,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 4100, 2230, 3891, 2417])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 61ms/step


array([[ 0.03112811,  0.00270622,  0.02091917, -0.01028411,  0.00108735,
        -0.04197252, -0.03361511,  0.03464837, -0.01296127, -0.04242287],
       [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,  0.00108735,
        -0.04197252, -0.03361511,  0.03464837, -0.01296127, -0.04242287],
       [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,  0.00108735,
        -0.04197252, -0.03361511,  0.03464837, -0.01296127, -0.04242287],
       [ 0.03112811,  0.00270622,  0.02091917, -0.01028411,  0.00108735,
        -0.04197252, -0.03361511,  0.03464837, -0.01296127, -0.04242287],
       [-0.01638373,  0.01433196,  0.02804383,  0.04002675, -0.00018103,
         0.00321428,  0.00964044,  0.01040549, -0.04174905, -0.01057873],
       [-0.01139801, -0.02679174, -0.01855575,  0.03856239, -0.04388597,
        -0.03039476, -0.00528153,  0.02034989, -0.0175235 ,  0.00594043],
       [ 0.00246538, -0.04481317,  0.04963833,  0.04975236, -0.00893155,
        -0.01045331,  0.03829323,  0.03166642